--bài tập 1
SELECT NAME 
FROM STUDENTS
WHERE MARKS>75
ORDER BY RIGHT(NAME,3),ID
--BAI TAP 2
SELECT USER_ID,
CONCAT(UPPER(LEFT(NAME,1)),LOWER(RIGHT(NAME,LENGTH(NAME)-1))) AS NAME
FROM USERS
--BAI TAP 3
SELECT MANUFACTURER,
'$'||ROUND(SUM(TOTAL_SALES)/1000000,0)||'MILLION'
FROM pharmacy_sales
GROUP BY MANUFACTURER
ORDER BY MANUFACTURER
-- BAI TAP 4
SELECT 
EXTRACT(MONTH FROM submit_date) AS MTH,
PRODUCT_ID,
ROUND(AVG(STARS),2) AS avg_stars
FROM reviews
GROUP BY submit_date,PRODUCT_ID
ORDER BY submit_date, PRODUCT_ID
-- BAI TAP 5
 SELECT SENDER_ID,
COUNT(message_id) AS  message_count
FROM messages
WHERE EXTRACT(MONTH FROM SENT_DATE)=8
AND EXTRACT(YEAR FROM SENT_DATE)=2022
GROUP BY SENDER_ID
ORDER BY  message_count DESC
LIMIT 2
-- BAI TAP 6
SELECT TWEET_ID
FROM TWEETS
WHERE LENGTH(CONTENT)>15
--BAI TAP 7
SELECT activity_date AS DAY,
COUNT(DISTINCT(user_id)) as active_users 
FROM Activity
WHERE activity_date BETWEEN "2019-06-28" AND "2019-07-28"
GROUP BY activity_date
-- BAI TAP 8
select 
COUNT(employees) AS number_of_employees
from employees
WHERE EXTRACT(MONTH FROM joining_date) BETWEEN 1 AND 7
AND EXTRACT(YEAR FROM joining_date)=2022
-- BAI TAP 9
select 
POSITION('a' IN FIRST_NAME) AS POSITION
FROM WORKER
WHERE FIRST_NAME='Amitah'
-- bai tap 10
select substring(title, length(winery)+2,4)
from winemag_p2
where country='Macedonia'
